### PR TITLE
Trying to send mjpeg via MultiMediaSourceMuxer

### PR DESCRIPTION
**Pull request by a-ucontrol**
Sent as is at the moment

https://github.com/ZLMediaKit/ZLMediaKit/issues/2161

### CODE REVIEW

**Comment by xia-chu** [comment]
Now you can improve the code of `JPEGRtpEncoder::inputFrame`.
I will improve other code on weekends

**Comment by a-ucontrol** [comment]
Submitted the changes that I managed to make today

**Comment by a-ucontrol** [comment]
Unfortunately, I could not get the image.

part of ffplay output:
```
[rtsp @ 0x7f164c000c00] SDP:
v=0
o=- 0 0 IN IP4 0.0.0.0
s=Streamed by ZLMediaKit(git hash:fb22a4a/2022-12-17T16:34:26+08:00,branch:feature/jpeg,build time:2022-12-17T13:01:39)
c=IN IP4 0.0.0.0
t=0 0
a=range:npt=now-
a=control:*
m=video 0 RTP/AVP 26
a=control:trackID=0
m=audio 0 RTP/AVP 98
a=rtpmap:98 opus/48000/2
a=control:trackID=1
```



```
[rtsp @ 0x7f164c000c00] Could not find codec parameters for stream 0 (Video: mjpeg, 1 reference frame, none(bt470bg/unknown/unknown, center)): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
Input #0, rtsp, from 'rtsp://admin:admin@127.0.0.1:5554/live/preview':
  Metadata:
    title           : Streamed by ZLMediaKit(git hash:fb22a4a/2022-12-17T16:34:26+08:00,branch:feature/jpeg,build time:2022-12-17T13:01:39)
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0, 0, 1/90000: Video: mjpeg, 1 reference frame, none(bt470bg/unknown/unknown, center), 90k tbr, 90k tbn, 90k tbc
  Stream #0:1, 252, 1/48000: Audio: opus, 48000 Hz, stereo, fltp

```

Tomorrow I will try to make a simple example of how I use ZLM

**Comment by a-ucontrol** [comment]
Now it works

```
2022-12-18 18:11:27.502 D Nexus2[13525-QThread] MediaSink.cpp:137 emitAllTrackReady | all track ready use 4ms
2022-12-18 18:11:27.502 I Nexus2[13525-QThread] MultiMediaSourceMuxer.cpp:362 onAllTrackReady | stream: schema://__defaultVhost__/app/stream , codec info: opus[48000/2/16] JPEG[0/0/0] 
2022-12-18 18:11:27.502 I Nexus2[13525-QThread] MediaSource.cpp:523 emitEvent | 媒体注册:rtsp://__defaultVhost__/live/preview
```

```
Input #0, rtsp, from 'rtsp://admin:admin@127.0.0.1:5554/live/preview':
  Metadata:
    title           : Streamed by ZLMediaKit(git hash:c295c6a/2022-12-17T19:44:10+03:00,branch:feature/jpeg,build time:2022-12-18T18:08:57)
  Duration: N/A, start: 1.860022, bitrate: N/A
  Stream #0:0: Video: mjpeg (Baseline), yuvj420p(pc, bt470bg/unknown/unknown), 640x480 [SAR 1:1 DAR 4:3], 50 tbr, 90k tbn, 90k tbc
  Stream #0:1: Audio: opus, 48000 Hz, stereo, fltp
[swscaler @ 0x7f00a0081b40] deprecated pixel format used, make sure you did set range correctly
  17.23 A-V: -0.020 fd=   1 aq=  196KB vq=  518KB sq=    0B f=0/0 
```
Still need to fix getVideoHeight(), getVideoWidth() and getVideoFps() in JPEGTrack

**Comment by a-ucontrol** [comment]
It works but may need to be improved

```
2022-12-19 18:16:20.061 I N2[12337-QThread] MultiMediaSourceMuxer.cpp:362 onAllTrackReady | stream: schema://__defaultVhost__/app/stream , codec info: opus[48000/2/16] JPEG[640/480/30] 
```

**Comment by xia-chu** [comment]
Do you see the log? 
```bash
2022-12-21 11:32:54.912 D MediaServer[63861-event poller 0] JPEGRtp.cpp:731 rtp_send_jpeg | RFC 2435 requires standard Huffman tables for jpeg

    Last message repeated 14 times
2022-12-21 11:32:55.438 D MediaServer[63861-event poller 0] JPEGRtp.cpp:731 rtp_send_jpeg | RFC 2435 requires standard Huffman tables for jpeg

    Last message repeated 13 times
```
You need set `directProxy` to `0` in config.ini file

**Comment by a-ucontrol** [comment]
When I send frames from a file, as in the previous message, there are no errors, with
```
mINI::Instance()[Rtsp::kDirectProxy] = 0;
```
But if send stream via ffmpeg -stream_loop -1 -re -i test-mjpeg-opus.mp4 -codec copy -f rtsp -rtsp_transport tcp rtsp://127.0.0.1:554/live/preview, there are errors

**Comment by xia-chu** [comment]
The bug is located and i fixed it，that's because there is a bug in the mjepg rtp unpacking code

**Comment by xia-chu** [comment]
I had add some comments in your code

**Comment by a-ucontrol** [comment]
//Do you want to exit the process when webrtc connections is zero?

In this case, in the destructor, we wait for the completion of all WebRtc sessions
```c++
MediaServer::~MediaServer()
{
    std::unique_lock<std::mutex> lock(webRtcMutex);
    while (!webRtcSessions.empty())
        webRtcConditionVariable.wait(lock); // This allows to remove sleep() before exiting main(). Is it possible to implement this in ZLM in a similar way?
}
```


// Now we support set pix_fmt type in JPEGFrame
It works, thanks


// How do you read mjpeg file all the time when read file eof?
He just reads in loop
```c++
while (!exit_flag) {
        ret = av_read_frame(fc, &packet);
        if (ret == 0) {
...
        } else {
...
            avformat_seek_file(fc, 0, 0, 0, 0, 0);
        }
    }
```

**Comment by xia-chu** [comment]
I do'nt think it's a good idea to exit the process when webrtc sessions become zero;
You start a mjpeg webrtc server(but none browser support mjpeg on webrtc), and wait for webrtc connection。
When last connection disconnected, you process exited, so how dou you restart it?

**Comment by xia-chu** [comment]
It's better to do like this:
- step 1: We listen the port and start webrtc server(and http/rtsp/rtmp...)
- step 2: We listen the event `kBroadcastNotFoundStream` and `kBroadcastStreamNoneReader` on `NoticeCenter`.
- step 3: When `kBroadcastNotFoundStream` event emited, we create a `MultiMediaSourceMuxer` and read file to input mjpeg frame to it in timer(or your new thread).
- step 4: When `kBroadcastStreamNoneReader` event emited, we stop read file and delete `MultiMediaSourceMuxer` .

**Comment by a-ucontrol** [comment]
A little wrong.
Webrts is for h264

Waiting for sessions to end here after SIGINT...
```c++
int main(int argc, char* argv[])
{
    AVFormatContext* fc = nullptr;
    if (avformat_open_input(&fc, APPLICATION_HOME "/test-h264-opus.mp4", 0, 0) < 0) {
        std::cerr << "file not found: " APPLICATION_HOME "/test-h264-opus.mp4\n";
        return -1;
    }

    signal(SIGINT, handleSignal);
    signal(SIGTERM, handleSignal);
    signal(SIGSTOP, handleSignal);
    signal(SIGKILL, handleSignal);
    signal(SIGABRT, handleSignal);
    int r = ({
        MediaServer mediaServer;
        MediaServer::Stream::Ptr stream_preview = mediaServer.createStream("live", "preview", mediakit::CodecH264, mediakit::CodecOpus);
         ffmpegRead(fc, stream_preview.get(), exit_flag);
    });

// Wait for all WebRtcSession finished

    return r;
}
```

**Comment by xia-chu** [comment]
All right, i think it's good code when your code is meet your needs;
I think your code looks OK!

**Comment by xia-chu** [comment]
I think our cooperation is very happy， thank for your contribution！

**Comment by a-ucontrol** [comment]
See if you can make small changes

This is needed to build without libusrsctp
```patch
diff --git a/CMakeLists.txt b/CMakeLists.txt
index adc5f768..f562d96d 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -50,6 +50,7 @@ option(ENABLE_SERVER "Enable Server" ON)
 option(ENABLE_SERVER_LIB "Enable server as android static library" OFF)
 option(ENABLE_SRT "Enable SRT" ON)
 option(ENABLE_TESTS "Enable Tests" ON)
+option(ENABLE_SCTP "Enable SCTP" ON)
 option(ENABLE_WEBRTC "Enable WebRTC" ON)
 option(ENABLE_X264 "Enable x264" OFF)
 option(ENABLE_WEPOLL "Enable wepoll" ON)
diff --git a/webrtc/CMakeLists.txt b/webrtc/CMakeLists.txt
index f2c4f65d..a00c0d36 100644
--- a/webrtc/CMakeLists.txt
+++ b/webrtc/CMakeLists.txt
@@ -38,6 +38,7 @@ set(LINK_LIBRARIES ${SRTP_LIBRARIES})
 set(COMPILE_DEFINITIONS)
 set(INCLUDE_DIRECTORIES)
 
+if(ENABLE_SCTP)
 find_package(SCTP QUIET)
 if(SCTP_FOUND)
   message(STATUS "found library: ${SCTP_INCLUDE_DIRS} ${SCTP_LIBRARIES}")
@@ -48,6 +49,7 @@ if(SCTP_FOUND)
   list(APPEND LINK_LIBRARIES ${SCTP_LIBRARIES})
   message(STATUS "WebRTC datachannel 功能已打开")
 endif()
+endif()
 
 file(GLOB WEBRTC_SRC_LIST
   ${CMAKE_CURRENT_SOURCE_DIR}/*.cpp
```

This is needed to build ZLM with **uclibc**
```patch
diff -Naur ZLMediaKit/3rdpart/ZLToolKit/src/Util/logger.h ZLMediaKit-m/3rdpart/ZLToolKit/src/Util/logger.h
--- ZLMediaKit/3rdpart/ZLToolKit/src/Util/logger.h      2022-11-11 12:00:14.000000000 +0300
+++ ZLMediaKit-m/3rdpart/ZLToolKit/src/Util/logger.h    2022-11-24 18:54:00.910286895 +0300
@@ -20,6 +20,7 @@
 #include "util.h"
 #include "List.h"
 #include "Thread/semaphore.h"
+#include <cstdarg>
 
 namespace toolkit {
 ```

**Comment by a-ucontrol** [comment]
I also think our cooperation is very happy, thank for your ZLMediaKit

**Comment by xia-chu** [comment]
I will merge your patch in next code merge window， thanks!

**Pull request merged**
